#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistema.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Loca_Car")]
	public partial class sistemaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCategoriacnh(Categoriacnh instance);
    partial void UpdateCategoriacnh(Categoriacnh instance);
    partial void DeleteCategoriacnh(Categoriacnh instance);
    partial void InsertCliente(Cliente instance);
    partial void UpdateCliente(Cliente instance);
    partial void DeleteCliente(Cliente instance);
    partial void InsertLocação(Locação instance);
    partial void UpdateLocação(Locação instance);
    partial void DeleteLocação(Locação instance);
    partial void InsertVeiculo(Veiculo instance);
    partial void UpdateVeiculo(Veiculo instance);
    partial void DeleteVeiculo(Veiculo instance);
    partial void InsertItensLocação(ItensLocação instance);
    partial void UpdateItensLocação(ItensLocação instance);
    partial void DeleteItensLocação(ItensLocação instance);
    partial void InsertStatusPagamento(StatusPagamento instance);
    partial void UpdateStatusPagamento(StatusPagamento instance);
    partial void DeleteStatusPagamento(StatusPagamento instance);
    partial void InsertContasReceber(ContasReceber instance);
    partial void UpdateContasReceber(ContasReceber instance);
    partial void DeleteContasReceber(ContasReceber instance);
    partial void InsertFuncionario(Funcionario instance);
    partial void UpdateFuncionario(Funcionario instance);
    partial void DeleteFuncionario(Funcionario instance);
    partial void InsertCarga_Horaria(Carga_Horaria instance);
    partial void UpdateCarga_Horaria(Carga_Horaria instance);
    partial void DeleteCarga_Horaria(Carga_Horaria instance);
    partial void InsertControleHorario(ControleHorario instance);
    partial void UpdateControleHorario(ControleHorario instance);
    partial void DeleteControleHorario(ControleHorario instance);
    partial void Inserttb_usuario(tb_usuario instance);
    partial void Updatetb_usuario(tb_usuario instance);
    partial void Deletetb_usuario(tb_usuario instance);
    #endregion
		
		public sistemaDataContext() : 
				base(global::sistema.DAL.Properties.Settings.Default.Loca_CarConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public sistemaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public sistemaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public sistemaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public sistemaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Categoriacnh> Categoriacnh
		{
			get
			{
				return this.GetTable<Categoriacnh>();
			}
		}
		
		public System.Data.Linq.Table<Cliente> Cliente
		{
			get
			{
				return this.GetTable<Cliente>();
			}
		}
		
		public System.Data.Linq.Table<Situacao> Situacao
		{
			get
			{
				return this.GetTable<Situacao>();
			}
		}
		
		public System.Data.Linq.Table<Locação> Locação
		{
			get
			{
				return this.GetTable<Locação>();
			}
		}
		
		public System.Data.Linq.Table<Veiculo> Veiculo
		{
			get
			{
				return this.GetTable<Veiculo>();
			}
		}
		
		public System.Data.Linq.Table<ItensLocação> ItensLocação
		{
			get
			{
				return this.GetTable<ItensLocação>();
			}
		}
		
		public System.Data.Linq.Table<StatusPagamento> StatusPagamento
		{
			get
			{
				return this.GetTable<StatusPagamento>();
			}
		}
		
		public System.Data.Linq.Table<ContasReceber> ContasReceber
		{
			get
			{
				return this.GetTable<ContasReceber>();
			}
		}
		
		public System.Data.Linq.Table<Funcionario> Funcionario
		{
			get
			{
				return this.GetTable<Funcionario>();
			}
		}
		
		public System.Data.Linq.Table<Carga_Horaria> Carga_Horaria
		{
			get
			{
				return this.GetTable<Carga_Horaria>();
			}
		}
		
		public System.Data.Linq.Table<ControleHorario> ControleHorario
		{
			get
			{
				return this.GetTable<ControleHorario>();
			}
		}
		
		public System.Data.Linq.Table<tb_usuario> tb_usuario
		{
			get
			{
				return this.GetTable<tb_usuario>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_categoriacnh")]
	public partial class Categoriacnh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CNH;
		
		private string _categoriacnh;
		
		private EntitySet<Cliente> _Cliente;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCNHChanging(string value);
    partial void OnCNHChanged();
    partial void OncategoriacnhChanging(string value);
    partial void OncategoriacnhChanged();
    #endregion
		
		public Categoriacnh()
		{
			this._Cliente = new EntitySet<Cliente>(new Action<Cliente>(this.attach_Cliente), new Action<Cliente>(this.detach_Cliente));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CNH", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CNH
		{
			get
			{
				return this._CNH;
			}
			set
			{
				if ((this._CNH != value))
				{
					this.OnCNHChanging(value);
					this.SendPropertyChanging();
					this._CNH = value;
					this.SendPropertyChanged("CNH");
					this.OnCNHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_categoriacnh", DbType="NVarChar(50)")]
		public string categoriacnh
		{
			get
			{
				return this._categoriacnh;
			}
			set
			{
				if ((this._categoriacnh != value))
				{
					this.OncategoriacnhChanging(value);
					this.SendPropertyChanging();
					this._categoriacnh = value;
					this.SendPropertyChanged("categoriacnh");
					this.OncategoriacnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Categoriacnh_Cliente", Storage="_Cliente", ThisKey="CNH", OtherKey="categoriacnh")]
		public EntitySet<Cliente> Cliente
		{
			get
			{
				return this._Cliente;
			}
			set
			{
				this._Cliente.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Cliente(Cliente entity)
		{
			this.SendPropertyChanging();
			entity.Categoriacnh1 = this;
		}
		
		private void detach_Cliente(Cliente entity)
		{
			this.SendPropertyChanging();
			entity.Categoriacnh1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_cliente")]
	public partial class Cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Código;
		
		private string _nome;
		
		private string _endereço;
		
		private System.Nullable<decimal> _telefone;
		
		private System.Nullable<System.DateTime> _data_de_nascimento;
		
		private System.Nullable<decimal> _cnh;
		
		private string _categoriacnh;
		
		private EntitySet<Locação> _Locação;
		
		private EntitySet<ItensLocação> _ItensLocação;
		
		private EntityRef<Categoriacnh> _Categoriacnh1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCódigoChanging(int value);
    partial void OnCódigoChanged();
    partial void OnnomeChanging(string value);
    partial void OnnomeChanged();
    partial void OnendereçoChanging(string value);
    partial void OnendereçoChanged();
    partial void OntelefoneChanging(System.Nullable<decimal> value);
    partial void OntelefoneChanged();
    partial void Ondata_de_nascimentoChanging(System.Nullable<System.DateTime> value);
    partial void Ondata_de_nascimentoChanged();
    partial void OncnhChanging(System.Nullable<decimal> value);
    partial void OncnhChanged();
    partial void OncategoriacnhChanging(string value);
    partial void OncategoriacnhChanged();
    #endregion
		
		public Cliente()
		{
			this._Locação = new EntitySet<Locação>(new Action<Locação>(this.attach_Locação), new Action<Locação>(this.detach_Locação));
			this._ItensLocação = new EntitySet<ItensLocação>(new Action<ItensLocação>(this.attach_ItensLocação), new Action<ItensLocação>(this.detach_ItensLocação));
			this._Categoriacnh1 = default(EntityRef<Categoriacnh>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_cliente", Storage="_Código", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Código
		{
			get
			{
				return this._Código;
			}
			set
			{
				if ((this._Código != value))
				{
					this.OnCódigoChanging(value);
					this.SendPropertyChanging();
					this._Código = value;
					this.SendPropertyChanged("Código");
					this.OnCódigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome", DbType="NVarChar(50)")]
		public string nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				if ((this._nome != value))
				{
					this.OnnomeChanging(value);
					this.SendPropertyChanging();
					this._nome = value;
					this.SendPropertyChanged("nome");
					this.OnnomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endereço", DbType="NVarChar(50)")]
		public string endereço
		{
			get
			{
				return this._endereço;
			}
			set
			{
				if ((this._endereço != value))
				{
					this.OnendereçoChanging(value);
					this.SendPropertyChanging();
					this._endereço = value;
					this.SendPropertyChanged("endereço");
					this.OnendereçoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefone", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> telefone
		{
			get
			{
				return this._telefone;
			}
			set
			{
				if ((this._telefone != value))
				{
					this.OntelefoneChanging(value);
					this.SendPropertyChanging();
					this._telefone = value;
					this.SendPropertyChanged("telefone");
					this.OntelefoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_de_nascimento", DbType="Date")]
		public System.Nullable<System.DateTime> data_de_nascimento
		{
			get
			{
				return this._data_de_nascimento;
			}
			set
			{
				if ((this._data_de_nascimento != value))
				{
					this.Ondata_de_nascimentoChanging(value);
					this.SendPropertyChanging();
					this._data_de_nascimento = value;
					this.SendPropertyChanged("data_de_nascimento");
					this.Ondata_de_nascimentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cnh", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> cnh
		{
			get
			{
				return this._cnh;
			}
			set
			{
				if ((this._cnh != value))
				{
					this.OncnhChanging(value);
					this.SendPropertyChanging();
					this._cnh = value;
					this.SendPropertyChanged("cnh");
					this.OncnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_categoriacnh", DbType="NVarChar(50)")]
		public string categoriacnh
		{
			get
			{
				return this._categoriacnh;
			}
			set
			{
				if ((this._categoriacnh != value))
				{
					if (this._Categoriacnh1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncategoriacnhChanging(value);
					this.SendPropertyChanging();
					this._categoriacnh = value;
					this.SendPropertyChanged("categoriacnh");
					this.OncategoriacnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Locação", Storage="_Locação", ThisKey="Código", OtherKey="id_pessoa")]
		public EntitySet<Locação> Locação
		{
			get
			{
				return this._Locação;
			}
			set
			{
				this._Locação.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_ItensLocação", Storage="_ItensLocação", ThisKey="Código", OtherKey="id_cliente")]
		public EntitySet<ItensLocação> ItensLocação
		{
			get
			{
				return this._ItensLocação;
			}
			set
			{
				this._ItensLocação.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Categoriacnh_Cliente", Storage="_Categoriacnh1", ThisKey="categoriacnh", OtherKey="CNH", IsForeignKey=true)]
		public Categoriacnh Categoriacnh1
		{
			get
			{
				return this._Categoriacnh1.Entity;
			}
			set
			{
				Categoriacnh previousValue = this._Categoriacnh1.Entity;
				if (((previousValue != value) 
							|| (this._Categoriacnh1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Categoriacnh1.Entity = null;
						previousValue.Cliente.Remove(this);
					}
					this._Categoriacnh1.Entity = value;
					if ((value != null))
					{
						value.Cliente.Add(this);
						this._categoriacnh = value.CNH;
					}
					else
					{
						this._categoriacnh = default(string);
					}
					this.SendPropertyChanged("Categoriacnh1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Locação(Locação entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = this;
		}
		
		private void detach_Locação(Locação entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = null;
		}
		
		private void attach_ItensLocação(ItensLocação entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = this;
		}
		
		private void detach_ItensLocação(ItensLocação entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_situaçao")]
	public partial class Situacao
	{
		
		private string _codigo;
		
		private string _situação;
		
		public Situacao()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo", DbType="NVarChar(50)")]
		public string codigo
		{
			get
			{
				return this._codigo;
			}
			set
			{
				if ((this._codigo != value))
				{
					this._codigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_situação", DbType="NVarChar(50)")]
		public string situação
		{
			get
			{
				return this._situação;
			}
			set
			{
				if ((this._situação != value))
				{
					this._situação = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_locação")]
	public partial class Locação : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_locação;
		
		private System.Nullable<decimal> _valor;
		
		private System.Nullable<decimal> _desconto;
		
		private System.Nullable<decimal> _valor_pago;
		
		private System.Nullable<int> _id_pessoa;
		
		private System.Nullable<int> _id_cliente;
		
		private EntitySet<ItensLocação> _ItensLocação;
		
		private EntitySet<ContasReceber> _ContasReceber;
		
		private EntityRef<Cliente> _Cliente;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_locaçãoChanging(int value);
    partial void Onid_locaçãoChanged();
    partial void OnvalorChanging(System.Nullable<decimal> value);
    partial void OnvalorChanged();
    partial void OndescontoChanging(System.Nullable<decimal> value);
    partial void OndescontoChanged();
    partial void Onvalor_pagoChanging(System.Nullable<decimal> value);
    partial void Onvalor_pagoChanged();
    partial void Onid_pessoaChanging(System.Nullable<int> value);
    partial void Onid_pessoaChanged();
    partial void Onid_clienteChanging(System.Nullable<int> value);
    partial void Onid_clienteChanged();
    #endregion
		
		public Locação()
		{
			this._ItensLocação = new EntitySet<ItensLocação>(new Action<ItensLocação>(this.attach_ItensLocação), new Action<ItensLocação>(this.detach_ItensLocação));
			this._ContasReceber = new EntitySet<ContasReceber>(new Action<ContasReceber>(this.attach_ContasReceber), new Action<ContasReceber>(this.detach_ContasReceber));
			this._Cliente = default(EntityRef<Cliente>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_locação", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_locação
		{
			get
			{
				return this._id_locação;
			}
			set
			{
				if ((this._id_locação != value))
				{
					this.Onid_locaçãoChanging(value);
					this.SendPropertyChanging();
					this._id_locação = value;
					this.SendPropertyChanged("id_locação");
					this.Onid_locaçãoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valor", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> valor
		{
			get
			{
				return this._valor;
			}
			set
			{
				if ((this._valor != value))
				{
					this.OnvalorChanging(value);
					this.SendPropertyChanging();
					this._valor = value;
					this.SendPropertyChanged("valor");
					this.OnvalorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desconto", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> desconto
		{
			get
			{
				return this._desconto;
			}
			set
			{
				if ((this._desconto != value))
				{
					this.OndescontoChanging(value);
					this.SendPropertyChanging();
					this._desconto = value;
					this.SendPropertyChanged("desconto");
					this.OndescontoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valor_pago", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> valor_pago
		{
			get
			{
				return this._valor_pago;
			}
			set
			{
				if ((this._valor_pago != value))
				{
					this.Onvalor_pagoChanging(value);
					this.SendPropertyChanging();
					this._valor_pago = value;
					this.SendPropertyChanged("valor_pago");
					this.Onvalor_pagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pessoa", DbType="Int")]
		public System.Nullable<int> id_pessoa
		{
			get
			{
				return this._id_pessoa;
			}
			set
			{
				if ((this._id_pessoa != value))
				{
					if (this._Cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_pessoaChanging(value);
					this.SendPropertyChanging();
					this._id_pessoa = value;
					this.SendPropertyChanged("id_pessoa");
					this.Onid_pessoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_cliente", DbType="Int")]
		public System.Nullable<int> id_cliente
		{
			get
			{
				return this._id_cliente;
			}
			set
			{
				if ((this._id_cliente != value))
				{
					this.Onid_clienteChanging(value);
					this.SendPropertyChanging();
					this._id_cliente = value;
					this.SendPropertyChanged("id_cliente");
					this.Onid_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Locação_ItensLocação", Storage="_ItensLocação", ThisKey="id_locação", OtherKey="id_locação")]
		public EntitySet<ItensLocação> ItensLocação
		{
			get
			{
				return this._ItensLocação;
			}
			set
			{
				this._ItensLocação.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Locação_ContasReceber", Storage="_ContasReceber", ThisKey="id_locação", OtherKey="id_locação")]
		public EntitySet<ContasReceber> ContasReceber
		{
			get
			{
				return this._ContasReceber;
			}
			set
			{
				this._ContasReceber.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Locação", Storage="_Cliente", ThisKey="id_pessoa", OtherKey="Código", IsForeignKey=true)]
		public Cliente Cliente
		{
			get
			{
				return this._Cliente.Entity;
			}
			set
			{
				Cliente previousValue = this._Cliente.Entity;
				if (((previousValue != value) 
							|| (this._Cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cliente.Entity = null;
						previousValue.Locação.Remove(this);
					}
					this._Cliente.Entity = value;
					if ((value != null))
					{
						value.Locação.Add(this);
						this._id_pessoa = value.Código;
					}
					else
					{
						this._id_pessoa = default(Nullable<int>);
					}
					this.SendPropertyChanged("Cliente");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ItensLocação(ItensLocação entity)
		{
			this.SendPropertyChanging();
			entity.Locação = this;
		}
		
		private void detach_ItensLocação(ItensLocação entity)
		{
			this.SendPropertyChanging();
			entity.Locação = null;
		}
		
		private void attach_ContasReceber(ContasReceber entity)
		{
			this.SendPropertyChanging();
			entity.Locação = this;
		}
		
		private void detach_ContasReceber(ContasReceber entity)
		{
			this.SendPropertyChanging();
			entity.Locação = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_veiculo")]
	public partial class Veiculo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Código;
		
		private string _fabricante;
		
		private string _modelo;
		
		private System.Nullable<decimal> _ano;
		
		private string _placa;
		
		private string _cor;
		
		private string _chassi;
		
		private System.Nullable<decimal> _renavam;
		
		private string _situação;
		
		private System.Nullable<decimal> _valor;
		
		private EntitySet<ItensLocação> _ItensLocação;
		
		private EntitySet<ContasReceber> _ContasReceber;
		
		private EntityRef<ItensLocação> _ItensLocação1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCódigoChanging(int value);
    partial void OnCódigoChanged();
    partial void OnfabricanteChanging(string value);
    partial void OnfabricanteChanged();
    partial void OnmodeloChanging(string value);
    partial void OnmodeloChanged();
    partial void OnanoChanging(System.Nullable<decimal> value);
    partial void OnanoChanged();
    partial void OnplacaChanging(string value);
    partial void OnplacaChanged();
    partial void OncorChanging(string value);
    partial void OncorChanged();
    partial void OnchassiChanging(string value);
    partial void OnchassiChanged();
    partial void OnrenavamChanging(System.Nullable<decimal> value);
    partial void OnrenavamChanged();
    partial void OnsituaçãoChanging(string value);
    partial void OnsituaçãoChanged();
    partial void OnvalorChanging(System.Nullable<decimal> value);
    partial void OnvalorChanged();
    #endregion
		
		public Veiculo()
		{
			this._ItensLocação = new EntitySet<ItensLocação>(new Action<ItensLocação>(this.attach_ItensLocação), new Action<ItensLocação>(this.detach_ItensLocação));
			this._ContasReceber = new EntitySet<ContasReceber>(new Action<ContasReceber>(this.attach_ContasReceber), new Action<ContasReceber>(this.detach_ContasReceber));
			this._ItensLocação1 = default(EntityRef<ItensLocação>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_veiculo", Storage="_Código", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Código
		{
			get
			{
				return this._Código;
			}
			set
			{
				if ((this._Código != value))
				{
					this.OnCódigoChanging(value);
					this.SendPropertyChanging();
					this._Código = value;
					this.SendPropertyChanged("Código");
					this.OnCódigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fabricante", DbType="NVarChar(50)")]
		public string fabricante
		{
			get
			{
				return this._fabricante;
			}
			set
			{
				if ((this._fabricante != value))
				{
					if (this._ItensLocação1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnfabricanteChanging(value);
					this.SendPropertyChanging();
					this._fabricante = value;
					this.SendPropertyChanged("fabricante");
					this.OnfabricanteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modelo", DbType="NChar(50)")]
		public string modelo
		{
			get
			{
				return this._modelo;
			}
			set
			{
				if ((this._modelo != value))
				{
					if (this._ItensLocação1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmodeloChanging(value);
					this.SendPropertyChanging();
					this._modelo = value;
					this.SendPropertyChanged("modelo");
					this.OnmodeloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ano", DbType="Decimal(25,0)")]
		public System.Nullable<decimal> ano
		{
			get
			{
				return this._ano;
			}
			set
			{
				if ((this._ano != value))
				{
					if (this._ItensLocação1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnanoChanging(value);
					this.SendPropertyChanging();
					this._ano = value;
					this.SendPropertyChanged("ano");
					this.OnanoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_placa", DbType="NVarChar(50)")]
		public string placa
		{
			get
			{
				return this._placa;
			}
			set
			{
				if ((this._placa != value))
				{
					if (this._ItensLocação1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnplacaChanging(value);
					this.SendPropertyChanging();
					this._placa = value;
					this.SendPropertyChanged("placa");
					this.OnplacaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cor", DbType="NVarChar(50)")]
		public string cor
		{
			get
			{
				return this._cor;
			}
			set
			{
				if ((this._cor != value))
				{
					if (this._ItensLocação1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncorChanging(value);
					this.SendPropertyChanging();
					this._cor = value;
					this.SendPropertyChanged("cor");
					this.OncorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chassi", DbType="NVarChar(50)")]
		public string chassi
		{
			get
			{
				return this._chassi;
			}
			set
			{
				if ((this._chassi != value))
				{
					this.OnchassiChanging(value);
					this.SendPropertyChanging();
					this._chassi = value;
					this.SendPropertyChanged("chassi");
					this.OnchassiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_renavam", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> renavam
		{
			get
			{
				return this._renavam;
			}
			set
			{
				if ((this._renavam != value))
				{
					this.OnrenavamChanging(value);
					this.SendPropertyChanging();
					this._renavam = value;
					this.SendPropertyChanged("renavam");
					this.OnrenavamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_situação", DbType="NVarChar(50)")]
		public string situação
		{
			get
			{
				return this._situação;
			}
			set
			{
				if ((this._situação != value))
				{
					if (this._ItensLocação1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnsituaçãoChanging(value);
					this.SendPropertyChanging();
					this._situação = value;
					this.SendPropertyChanged("situação");
					this.OnsituaçãoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valor", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> valor
		{
			get
			{
				return this._valor;
			}
			set
			{
				if ((this._valor != value))
				{
					if (this._ItensLocação1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnvalorChanging(value);
					this.SendPropertyChanging();
					this._valor = value;
					this.SendPropertyChanged("valor");
					this.OnvalorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Veiculo_ItensLocação", Storage="_ItensLocação", ThisKey="Código,modelo,valor,fabricante,cor,ano,placa,situação", OtherKey="id_veiculo,modelo,valor,fabricante,cor,ano,placa,situação")]
		public EntitySet<ItensLocação> ItensLocação
		{
			get
			{
				return this._ItensLocação;
			}
			set
			{
				this._ItensLocação.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Veiculo_ContasReceber", Storage="_ContasReceber", ThisKey="Código,situação", OtherKey="id_veiculo,situação")]
		public EntitySet<ContasReceber> ContasReceber
		{
			get
			{
				return this._ContasReceber;
			}
			set
			{
				this._ContasReceber.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ItensLocação_Veiculo", Storage="_ItensLocação1", ThisKey="valor,modelo,situação,fabricante,ano,placa,cor", OtherKey="valor,modelo,situação,fabricante,ano,placa,cor", IsForeignKey=true)]
		public ItensLocação ItensLocação1
		{
			get
			{
				return this._ItensLocação1.Entity;
			}
			set
			{
				ItensLocação previousValue = this._ItensLocação1.Entity;
				if (((previousValue != value) 
							|| (this._ItensLocação1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ItensLocação1.Entity = null;
						previousValue.Veiculo1.Remove(this);
					}
					this._ItensLocação1.Entity = value;
					if ((value != null))
					{
						value.Veiculo1.Add(this);
						this._valor = value.valor;
						this._modelo = value.modelo;
						this._situação = value.situação;
						this._fabricante = value.fabricante;
						this._ano = value.ano;
						this._placa = value.placa;
						this._cor = value.cor;
					}
					else
					{
						this._valor = default(Nullable<decimal>);
						this._modelo = default(string);
						this._situação = default(string);
						this._fabricante = default(string);
						this._ano = default(Nullable<decimal>);
						this._placa = default(string);
						this._cor = default(string);
					}
					this.SendPropertyChanged("ItensLocação1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ItensLocação(ItensLocação entity)
		{
			this.SendPropertyChanging();
			entity.Veiculo = this;
		}
		
		private void detach_ItensLocação(ItensLocação entity)
		{
			this.SendPropertyChanging();
			entity.Veiculo = null;
		}
		
		private void attach_ContasReceber(ContasReceber entity)
		{
			this.SendPropertyChanging();
			entity.Veiculo = this;
		}
		
		private void detach_ContasReceber(ContasReceber entity)
		{
			this.SendPropertyChanging();
			entity.Veiculo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_itens_locação")]
	public partial class ItensLocação : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_item;
		
		private System.Nullable<int> _id_veiculo;
		
		private System.Nullable<int> _id_locação;
		
		private System.Nullable<decimal> _valor;
		
		private System.Nullable<int> _quantidade;
		
		private System.Nullable<int> _id_cliente;
		
		private string _modelo;
		
		private string _situação;
		
		private string _fabricante;
		
		private System.Nullable<decimal> _ano;
		
		private string _placa;
		
		private string _cor;
		
		private EntitySet<Veiculo> _Veiculo1;
		
		private EntitySet<ContasReceber> _ContasReceber1;
		
		private EntityRef<Cliente> _Cliente;
		
		private EntityRef<Veiculo> _Veiculo;
		
		private EntityRef<Locação> _Locação;
		
		private EntityRef<ContasReceber> _ContasReceber;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_itemChanging(int value);
    partial void Onid_itemChanged();
    partial void Onid_veiculoChanging(System.Nullable<int> value);
    partial void Onid_veiculoChanged();
    partial void Onid_locaçãoChanging(System.Nullable<int> value);
    partial void Onid_locaçãoChanged();
    partial void OnvalorChanging(System.Nullable<decimal> value);
    partial void OnvalorChanged();
    partial void OnquantidadeChanging(System.Nullable<int> value);
    partial void OnquantidadeChanged();
    partial void Onid_clienteChanging(System.Nullable<int> value);
    partial void Onid_clienteChanged();
    partial void OnmodeloChanging(string value);
    partial void OnmodeloChanged();
    partial void OnsituaçãoChanging(string value);
    partial void OnsituaçãoChanged();
    partial void OnfabricanteChanging(string value);
    partial void OnfabricanteChanged();
    partial void OnanoChanging(System.Nullable<decimal> value);
    partial void OnanoChanged();
    partial void OnplacaChanging(string value);
    partial void OnplacaChanged();
    partial void OncorChanging(string value);
    partial void OncorChanged();
    #endregion
		
		public ItensLocação()
		{
			this._Veiculo1 = new EntitySet<Veiculo>(new Action<Veiculo>(this.attach_Veiculo1), new Action<Veiculo>(this.detach_Veiculo1));
			this._ContasReceber1 = new EntitySet<ContasReceber>(new Action<ContasReceber>(this.attach_ContasReceber1), new Action<ContasReceber>(this.detach_ContasReceber1));
			this._Cliente = default(EntityRef<Cliente>);
			this._Veiculo = default(EntityRef<Veiculo>);
			this._Locação = default(EntityRef<Locação>);
			this._ContasReceber = default(EntityRef<ContasReceber>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_item", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_item
		{
			get
			{
				return this._id_item;
			}
			set
			{
				if ((this._id_item != value))
				{
					this.Onid_itemChanging(value);
					this.SendPropertyChanging();
					this._id_item = value;
					this.SendPropertyChanged("id_item");
					this.Onid_itemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_veiculo", DbType="Int")]
		public System.Nullable<int> id_veiculo
		{
			get
			{
				return this._id_veiculo;
			}
			set
			{
				if ((this._id_veiculo != value))
				{
					if ((this._Veiculo.HasLoadedOrAssignedValue || this._ContasReceber.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_veiculoChanging(value);
					this.SendPropertyChanging();
					this._id_veiculo = value;
					this.SendPropertyChanged("id_veiculo");
					this.Onid_veiculoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_locação", DbType="Int")]
		public System.Nullable<int> id_locação
		{
			get
			{
				return this._id_locação;
			}
			set
			{
				if ((this._id_locação != value))
				{
					if (this._Locação.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_locaçãoChanging(value);
					this.SendPropertyChanging();
					this._id_locação = value;
					this.SendPropertyChanged("id_locação");
					this.Onid_locaçãoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valor", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> valor
		{
			get
			{
				return this._valor;
			}
			set
			{
				if ((this._valor != value))
				{
					if (this._Veiculo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnvalorChanging(value);
					this.SendPropertyChanging();
					this._valor = value;
					this.SendPropertyChanged("valor");
					this.OnvalorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantidade", DbType="Int")]
		public System.Nullable<int> quantidade
		{
			get
			{
				return this._quantidade;
			}
			set
			{
				if ((this._quantidade != value))
				{
					this.OnquantidadeChanging(value);
					this.SendPropertyChanging();
					this._quantidade = value;
					this.SendPropertyChanged("quantidade");
					this.OnquantidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_cliente", DbType="Int")]
		public System.Nullable<int> id_cliente
		{
			get
			{
				return this._id_cliente;
			}
			set
			{
				if ((this._id_cliente != value))
				{
					if (this._Cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_clienteChanging(value);
					this.SendPropertyChanging();
					this._id_cliente = value;
					this.SendPropertyChanged("id_cliente");
					this.Onid_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modelo", DbType="NChar(10)")]
		public string modelo
		{
			get
			{
				return this._modelo;
			}
			set
			{
				if ((this._modelo != value))
				{
					if (this._Veiculo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmodeloChanging(value);
					this.SendPropertyChanging();
					this._modelo = value;
					this.SendPropertyChanged("modelo");
					this.OnmodeloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_situação", DbType="NVarChar(50)")]
		public string situação
		{
			get
			{
				return this._situação;
			}
			set
			{
				if ((this._situação != value))
				{
					if ((this._Veiculo.HasLoadedOrAssignedValue || this._ContasReceber.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnsituaçãoChanging(value);
					this.SendPropertyChanging();
					this._situação = value;
					this.SendPropertyChanged("situação");
					this.OnsituaçãoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fabricante", DbType="NVarChar(50)")]
		public string fabricante
		{
			get
			{
				return this._fabricante;
			}
			set
			{
				if ((this._fabricante != value))
				{
					if (this._Veiculo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnfabricanteChanging(value);
					this.SendPropertyChanging();
					this._fabricante = value;
					this.SendPropertyChanged("fabricante");
					this.OnfabricanteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ano", DbType="Decimal(25,0)")]
		public System.Nullable<decimal> ano
		{
			get
			{
				return this._ano;
			}
			set
			{
				if ((this._ano != value))
				{
					if (this._Veiculo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnanoChanging(value);
					this.SendPropertyChanging();
					this._ano = value;
					this.SendPropertyChanged("ano");
					this.OnanoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_placa", DbType="NVarChar(50)")]
		public string placa
		{
			get
			{
				return this._placa;
			}
			set
			{
				if ((this._placa != value))
				{
					if (this._Veiculo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnplacaChanging(value);
					this.SendPropertyChanging();
					this._placa = value;
					this.SendPropertyChanged("placa");
					this.OnplacaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cor", DbType="NVarChar(50)")]
		public string cor
		{
			get
			{
				return this._cor;
			}
			set
			{
				if ((this._cor != value))
				{
					if (this._Veiculo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncorChanging(value);
					this.SendPropertyChanging();
					this._cor = value;
					this.SendPropertyChanged("cor");
					this.OncorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ItensLocação_Veiculo", Storage="_Veiculo1", ThisKey="valor,modelo,situação,fabricante,ano,placa,cor", OtherKey="valor,modelo,situação,fabricante,ano,placa,cor")]
		public EntitySet<Veiculo> Veiculo1
		{
			get
			{
				return this._Veiculo1;
			}
			set
			{
				this._Veiculo1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ItensLocação_ContasReceber", Storage="_ContasReceber1", ThisKey="id_veiculo", OtherKey="id_veiculo")]
		public EntitySet<ContasReceber> ContasReceber1
		{
			get
			{
				return this._ContasReceber1;
			}
			set
			{
				this._ContasReceber1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_ItensLocação", Storage="_Cliente", ThisKey="id_cliente", OtherKey="Código", IsForeignKey=true)]
		public Cliente Cliente
		{
			get
			{
				return this._Cliente.Entity;
			}
			set
			{
				Cliente previousValue = this._Cliente.Entity;
				if (((previousValue != value) 
							|| (this._Cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cliente.Entity = null;
						previousValue.ItensLocação.Remove(this);
					}
					this._Cliente.Entity = value;
					if ((value != null))
					{
						value.ItensLocação.Add(this);
						this._id_cliente = value.Código;
					}
					else
					{
						this._id_cliente = default(Nullable<int>);
					}
					this.SendPropertyChanged("Cliente");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Veiculo_ItensLocação", Storage="_Veiculo", ThisKey="id_veiculo,modelo,valor,fabricante,cor,ano,placa,situação", OtherKey="Código,modelo,valor,fabricante,cor,ano,placa,situação", IsForeignKey=true)]
		public Veiculo Veiculo
		{
			get
			{
				return this._Veiculo.Entity;
			}
			set
			{
				Veiculo previousValue = this._Veiculo.Entity;
				if (((previousValue != value) 
							|| (this._Veiculo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Veiculo.Entity = null;
						previousValue.ItensLocação.Remove(this);
					}
					this._Veiculo.Entity = value;
					if ((value != null))
					{
						value.ItensLocação.Add(this);
						this._id_veiculo = value.Código;
						this._modelo = value.modelo;
						this._valor = value.valor;
						this._fabricante = value.fabricante;
						this._cor = value.cor;
						this._ano = value.ano;
						this._placa = value.placa;
						this._situação = value.situação;
					}
					else
					{
						this._id_veiculo = default(Nullable<int>);
						this._modelo = default(string);
						this._valor = default(Nullable<decimal>);
						this._fabricante = default(string);
						this._cor = default(string);
						this._ano = default(Nullable<decimal>);
						this._placa = default(string);
						this._situação = default(string);
					}
					this.SendPropertyChanged("Veiculo");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Locação_ItensLocação", Storage="_Locação", ThisKey="id_locação", OtherKey="id_locação", IsForeignKey=true)]
		public Locação Locação
		{
			get
			{
				return this._Locação.Entity;
			}
			set
			{
				Locação previousValue = this._Locação.Entity;
				if (((previousValue != value) 
							|| (this._Locação.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Locação.Entity = null;
						previousValue.ItensLocação.Remove(this);
					}
					this._Locação.Entity = value;
					if ((value != null))
					{
						value.ItensLocação.Add(this);
						this._id_locação = value.id_locação;
					}
					else
					{
						this._id_locação = default(Nullable<int>);
					}
					this.SendPropertyChanged("Locação");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ContasReceber_ItensLocação", Storage="_ContasReceber", ThisKey="id_veiculo,situação", OtherKey="id_veiculo,situação", IsForeignKey=true)]
		public ContasReceber ContasReceber
		{
			get
			{
				return this._ContasReceber.Entity;
			}
			set
			{
				ContasReceber previousValue = this._ContasReceber.Entity;
				if (((previousValue != value) 
							|| (this._ContasReceber.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ContasReceber.Entity = null;
						previousValue.ItensLocação.Remove(this);
					}
					this._ContasReceber.Entity = value;
					if ((value != null))
					{
						value.ItensLocação.Add(this);
						this._id_veiculo = value.id_veiculo;
						this._situação = value.situação;
					}
					else
					{
						this._id_veiculo = default(Nullable<int>);
						this._situação = default(string);
					}
					this.SendPropertyChanged("ContasReceber");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Veiculo1(Veiculo entity)
		{
			this.SendPropertyChanging();
			entity.ItensLocação1 = this;
		}
		
		private void detach_Veiculo1(Veiculo entity)
		{
			this.SendPropertyChanging();
			entity.ItensLocação1 = null;
		}
		
		private void attach_ContasReceber1(ContasReceber entity)
		{
			this.SendPropertyChanging();
			entity.ItensLocação1 = this;
		}
		
		private void detach_ContasReceber1(ContasReceber entity)
		{
			this.SendPropertyChanging();
			entity.ItensLocação1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_status")]
	public partial class StatusPagamento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CódigoStatus;
		
		private string _Status;
		
		private EntitySet<ContasReceber> _ContasReceber;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCódigoStatusChanging(int value);
    partial void OnCódigoStatusChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    #endregion
		
		public StatusPagamento()
		{
			this._ContasReceber = new EntitySet<ContasReceber>(new Action<ContasReceber>(this.attach_ContasReceber), new Action<ContasReceber>(this.detach_ContasReceber));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_status", Storage="_CódigoStatus", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CódigoStatus
		{
			get
			{
				return this._CódigoStatus;
			}
			set
			{
				if ((this._CódigoStatus != value))
				{
					this.OnCódigoStatusChanging(value);
					this.SendPropertyChanging();
					this._CódigoStatus = value;
					this.SendPropertyChanged("CódigoStatus");
					this.OnCódigoStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="status", Storage="_Status", DbType="NVarChar(50)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="StatusPagamento_ContasReceber", Storage="_ContasReceber", ThisKey="CódigoStatus", OtherKey="CódigoSatus")]
		public EntitySet<ContasReceber> ContasReceber
		{
			get
			{
				return this._ContasReceber;
			}
			set
			{
				this._ContasReceber.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ContasReceber(ContasReceber entity)
		{
			this.SendPropertyChanging();
			entity.StatusPagamento = this;
		}
		
		private void detach_ContasReceber(ContasReceber entity)
		{
			this.SendPropertyChanging();
			entity.StatusPagamento = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_contas_receber")]
	public partial class ContasReceber : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CódigoConta;
		
		private System.Nullable<System.DateTime> _DataLocação;
		
		private System.Nullable<System.DateTime> _DataDevolução;
		
		private System.Nullable<System.DateTime> _DataPagamento;
		
		private System.Nullable<int> _id_locação;
		
		private System.Nullable<int> _CódigoSatus;
		
		private System.Nullable<int> _id_veiculo;
		
		private string _situação;
		
		private EntitySet<ItensLocação> _ItensLocação;
		
		private EntityRef<Locação> _Locação;
		
		private EntityRef<StatusPagamento> _StatusPagamento;
		
		private EntityRef<Veiculo> _Veiculo;
		
		private EntityRef<ItensLocação> _ItensLocação1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCódigoContaChanging(int value);
    partial void OnCódigoContaChanged();
    partial void OnDataLocaçãoChanging(System.Nullable<System.DateTime> value);
    partial void OnDataLocaçãoChanged();
    partial void OnDataDevoluçãoChanging(System.Nullable<System.DateTime> value);
    partial void OnDataDevoluçãoChanged();
    partial void OnDataPagamentoChanging(System.Nullable<System.DateTime> value);
    partial void OnDataPagamentoChanged();
    partial void Onid_locaçãoChanging(System.Nullable<int> value);
    partial void Onid_locaçãoChanged();
    partial void OnCódigoSatusChanging(System.Nullable<int> value);
    partial void OnCódigoSatusChanged();
    partial void Onid_veiculoChanging(System.Nullable<int> value);
    partial void Onid_veiculoChanged();
    partial void OnsituaçãoChanging(string value);
    partial void OnsituaçãoChanged();
    #endregion
		
		public ContasReceber()
		{
			this._ItensLocação = new EntitySet<ItensLocação>(new Action<ItensLocação>(this.attach_ItensLocação), new Action<ItensLocação>(this.detach_ItensLocação));
			this._Locação = default(EntityRef<Locação>);
			this._StatusPagamento = default(EntityRef<StatusPagamento>);
			this._Veiculo = default(EntityRef<Veiculo>);
			this._ItensLocação1 = default(EntityRef<ItensLocação>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_conta", Storage="_CódigoConta", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CódigoConta
		{
			get
			{
				return this._CódigoConta;
			}
			set
			{
				if ((this._CódigoConta != value))
				{
					this.OnCódigoContaChanging(value);
					this.SendPropertyChanging();
					this._CódigoConta = value;
					this.SendPropertyChanged("CódigoConta");
					this.OnCódigoContaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="data_locação", Storage="_DataLocação", DbType="DateTime")]
		public System.Nullable<System.DateTime> DataLocação
		{
			get
			{
				return this._DataLocação;
			}
			set
			{
				if ((this._DataLocação != value))
				{
					this.OnDataLocaçãoChanging(value);
					this.SendPropertyChanging();
					this._DataLocação = value;
					this.SendPropertyChanged("DataLocação");
					this.OnDataLocaçãoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="data_devolução", Storage="_DataDevolução", DbType="DateTime")]
		public System.Nullable<System.DateTime> DataDevolução
		{
			get
			{
				return this._DataDevolução;
			}
			set
			{
				if ((this._DataDevolução != value))
				{
					this.OnDataDevoluçãoChanging(value);
					this.SendPropertyChanging();
					this._DataDevolução = value;
					this.SendPropertyChanged("DataDevolução");
					this.OnDataDevoluçãoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="data_pagamento", Storage="_DataPagamento", DbType="DateTime")]
		public System.Nullable<System.DateTime> DataPagamento
		{
			get
			{
				return this._DataPagamento;
			}
			set
			{
				if ((this._DataPagamento != value))
				{
					this.OnDataPagamentoChanging(value);
					this.SendPropertyChanging();
					this._DataPagamento = value;
					this.SendPropertyChanged("DataPagamento");
					this.OnDataPagamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_locação", DbType="Int")]
		public System.Nullable<int> id_locação
		{
			get
			{
				return this._id_locação;
			}
			set
			{
				if ((this._id_locação != value))
				{
					if (this._Locação.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_locaçãoChanging(value);
					this.SendPropertyChanging();
					this._id_locação = value;
					this.SendPropertyChanged("id_locação");
					this.Onid_locaçãoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_status", Storage="_CódigoSatus", DbType="Int")]
		public System.Nullable<int> CódigoSatus
		{
			get
			{
				return this._CódigoSatus;
			}
			set
			{
				if ((this._CódigoSatus != value))
				{
					this.OnCódigoSatusChanging(value);
					this.SendPropertyChanging();
					this._CódigoSatus = value;
					this.SendPropertyChanged("CódigoSatus");
					this.OnCódigoSatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_veiculo", DbType="Int")]
		public System.Nullable<int> id_veiculo
		{
			get
			{
				return this._id_veiculo;
			}
			set
			{
				if ((this._id_veiculo != value))
				{
					if ((this._Veiculo.HasLoadedOrAssignedValue || this._ItensLocação1.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_veiculoChanging(value);
					this.SendPropertyChanging();
					this._id_veiculo = value;
					this.SendPropertyChanged("id_veiculo");
					this.Onid_veiculoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_situação", DbType="NVarChar(50)")]
		public string situação
		{
			get
			{
				return this._situação;
			}
			set
			{
				if ((this._situação != value))
				{
					if (this._Veiculo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnsituaçãoChanging(value);
					this.SendPropertyChanging();
					this._situação = value;
					this.SendPropertyChanged("situação");
					this.OnsituaçãoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ContasReceber_ItensLocação", Storage="_ItensLocação", ThisKey="id_veiculo,situação", OtherKey="id_veiculo,situação")]
		public EntitySet<ItensLocação> ItensLocação
		{
			get
			{
				return this._ItensLocação;
			}
			set
			{
				this._ItensLocação.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Locação_ContasReceber", Storage="_Locação", ThisKey="id_locação", OtherKey="id_locação", IsForeignKey=true)]
		public Locação Locação
		{
			get
			{
				return this._Locação.Entity;
			}
			set
			{
				Locação previousValue = this._Locação.Entity;
				if (((previousValue != value) 
							|| (this._Locação.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Locação.Entity = null;
						previousValue.ContasReceber.Remove(this);
					}
					this._Locação.Entity = value;
					if ((value != null))
					{
						value.ContasReceber.Add(this);
						this._id_locação = value.id_locação;
					}
					else
					{
						this._id_locação = default(Nullable<int>);
					}
					this.SendPropertyChanged("Locação");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="StatusPagamento_ContasReceber", Storage="_StatusPagamento", ThisKey="CódigoSatus", OtherKey="CódigoStatus", IsForeignKey=true)]
		public StatusPagamento StatusPagamento
		{
			get
			{
				return this._StatusPagamento.Entity;
			}
			set
			{
				StatusPagamento previousValue = this._StatusPagamento.Entity;
				if (((previousValue != value) 
							|| (this._StatusPagamento.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._StatusPagamento.Entity = null;
						previousValue.ContasReceber.Remove(this);
					}
					this._StatusPagamento.Entity = value;
					if ((value != null))
					{
						value.ContasReceber.Add(this);
						this._CódigoSatus = value.CódigoStatus;
					}
					else
					{
						this._CódigoSatus = default(Nullable<int>);
					}
					this.SendPropertyChanged("StatusPagamento");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Veiculo_ContasReceber", Storage="_Veiculo", ThisKey="id_veiculo,situação", OtherKey="Código,situação", IsForeignKey=true)]
		public Veiculo Veiculo
		{
			get
			{
				return this._Veiculo.Entity;
			}
			set
			{
				Veiculo previousValue = this._Veiculo.Entity;
				if (((previousValue != value) 
							|| (this._Veiculo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Veiculo.Entity = null;
						previousValue.ContasReceber.Remove(this);
					}
					this._Veiculo.Entity = value;
					if ((value != null))
					{
						value.ContasReceber.Add(this);
						this._id_veiculo = value.Código;
						this._situação = value.situação;
					}
					else
					{
						this._id_veiculo = default(Nullable<int>);
						this._situação = default(string);
					}
					this.SendPropertyChanged("Veiculo");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ItensLocação_ContasReceber", Storage="_ItensLocação1", ThisKey="id_veiculo", OtherKey="id_veiculo", IsForeignKey=true)]
		public ItensLocação ItensLocação1
		{
			get
			{
				return this._ItensLocação1.Entity;
			}
			set
			{
				ItensLocação previousValue = this._ItensLocação1.Entity;
				if (((previousValue != value) 
							|| (this._ItensLocação1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ItensLocação1.Entity = null;
						previousValue.ContasReceber1.Remove(this);
					}
					this._ItensLocação1.Entity = value;
					if ((value != null))
					{
						value.ContasReceber1.Add(this);
						this._id_veiculo = value.id_veiculo;
					}
					else
					{
						this._id_veiculo = default(Nullable<int>);
					}
					this.SendPropertyChanged("ItensLocação1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ItensLocação(ItensLocação entity)
		{
			this.SendPropertyChanging();
			entity.ContasReceber = this;
		}
		
		private void detach_ItensLocação(ItensLocação entity)
		{
			this.SendPropertyChanging();
			entity.ContasReceber = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_funcionario")]
	public partial class Funcionario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Funcionario;
		
		private string _Nome;
		
		private string _Endereco;
		
		private System.Nullable<decimal> _Telefone;
		
		private System.Nullable<System.DateTime> _DatadeNascimento;
		
		private System.Nullable<decimal> _Salario;
		
		private string _Situacao;
		
		private string _Funcao;
		
		private System.Nullable<System.TimeSpan> _HorarioEntrada;
		
		private string _CargaHoraria;
		
		private EntityRef<Carga_Horaria> _Carga_Horaria;
		
		private EntityRef<ControleHorario> _ControleHorario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_FuncionarioChanging(int value);
    partial void OnID_FuncionarioChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnEnderecoChanging(string value);
    partial void OnEnderecoChanged();
    partial void OnTelefoneChanging(System.Nullable<decimal> value);
    partial void OnTelefoneChanged();
    partial void OnDatadeNascimentoChanging(System.Nullable<System.DateTime> value);
    partial void OnDatadeNascimentoChanged();
    partial void OnSalarioChanging(System.Nullable<decimal> value);
    partial void OnSalarioChanged();
    partial void OnSituacaoChanging(string value);
    partial void OnSituacaoChanged();
    partial void OnFuncaoChanging(string value);
    partial void OnFuncaoChanged();
    partial void OnHorarioEntradaChanging(System.Nullable<System.TimeSpan> value);
    partial void OnHorarioEntradaChanged();
    partial void OnCargaHorariaChanging(string value);
    partial void OnCargaHorariaChanged();
    #endregion
		
		public Funcionario()
		{
			this._Carga_Horaria = default(EntityRef<Carga_Horaria>);
			this._ControleHorario = default(EntityRef<ControleHorario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Funcionario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Funcionario
		{
			get
			{
				return this._ID_Funcionario;
			}
			set
			{
				if ((this._ID_Funcionario != value))
				{
					this.OnID_FuncionarioChanging(value);
					this.SendPropertyChanging();
					this._ID_Funcionario = value;
					this.SendPropertyChanged("ID_Funcionario");
					this.OnID_FuncionarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="NVarChar(50)")]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					if (this._ControleHorario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Endereco", DbType="NVarChar(50)")]
		public string Endereco
		{
			get
			{
				return this._Endereco;
			}
			set
			{
				if ((this._Endereco != value))
				{
					this.OnEnderecoChanging(value);
					this.SendPropertyChanging();
					this._Endereco = value;
					this.SendPropertyChanged("Endereco");
					this.OnEnderecoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefone", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Telefone
		{
			get
			{
				return this._Telefone;
			}
			set
			{
				if ((this._Telefone != value))
				{
					this.OnTelefoneChanging(value);
					this.SendPropertyChanging();
					this._Telefone = value;
					this.SendPropertyChanged("Telefone");
					this.OnTelefoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DatadeNascimento", DbType="Date")]
		public System.Nullable<System.DateTime> DatadeNascimento
		{
			get
			{
				return this._DatadeNascimento;
			}
			set
			{
				if ((this._DatadeNascimento != value))
				{
					this.OnDatadeNascimentoChanging(value);
					this.SendPropertyChanging();
					this._DatadeNascimento = value;
					this.SendPropertyChanged("DatadeNascimento");
					this.OnDatadeNascimentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Salario", DbType="Money")]
		public System.Nullable<decimal> Salario
		{
			get
			{
				return this._Salario;
			}
			set
			{
				if ((this._Salario != value))
				{
					this.OnSalarioChanging(value);
					this.SendPropertyChanging();
					this._Salario = value;
					this.SendPropertyChanged("Salario");
					this.OnSalarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Situacao", DbType="NVarChar(50)")]
		public string Situacao
		{
			get
			{
				return this._Situacao;
			}
			set
			{
				if ((this._Situacao != value))
				{
					this.OnSituacaoChanging(value);
					this.SendPropertyChanging();
					this._Situacao = value;
					this.SendPropertyChanged("Situacao");
					this.OnSituacaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Funcao", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Funcao
		{
			get
			{
				return this._Funcao;
			}
			set
			{
				if ((this._Funcao != value))
				{
					this.OnFuncaoChanging(value);
					this.SendPropertyChanging();
					this._Funcao = value;
					this.SendPropertyChanged("Funcao");
					this.OnFuncaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HorarioEntrada", DbType="Time")]
		public System.Nullable<System.TimeSpan> HorarioEntrada
		{
			get
			{
				return this._HorarioEntrada;
			}
			set
			{
				if ((this._HorarioEntrada != value))
				{
					this.OnHorarioEntradaChanging(value);
					this.SendPropertyChanging();
					this._HorarioEntrada = value;
					this.SendPropertyChanged("HorarioEntrada");
					this.OnHorarioEntradaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CargaHoraria", DbType="NVarChar(50)")]
		public string CargaHoraria
		{
			get
			{
				return this._CargaHoraria;
			}
			set
			{
				if ((this._CargaHoraria != value))
				{
					if ((this._Carga_Horaria.HasLoadedOrAssignedValue || this._ControleHorario.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCargaHorariaChanging(value);
					this.SendPropertyChanging();
					this._CargaHoraria = value;
					this.SendPropertyChanged("CargaHoraria");
					this.OnCargaHorariaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Carga_Horaria_Funcionario", Storage="_Carga_Horaria", ThisKey="CargaHoraria", OtherKey="CargaHoraria", IsForeignKey=true)]
		public Carga_Horaria Carga_Horaria
		{
			get
			{
				return this._Carga_Horaria.Entity;
			}
			set
			{
				Carga_Horaria previousValue = this._Carga_Horaria.Entity;
				if (((previousValue != value) 
							|| (this._Carga_Horaria.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Carga_Horaria.Entity = null;
						previousValue.Funcionario.Remove(this);
					}
					this._Carga_Horaria.Entity = value;
					if ((value != null))
					{
						value.Funcionario.Add(this);
						this._CargaHoraria = value.CargaHoraria;
					}
					else
					{
						this._CargaHoraria = default(string);
					}
					this.SendPropertyChanged("Carga_Horaria");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ControleHorario_Funcionario", Storage="_ControleHorario", ThisKey="CargaHoraria,Nome", OtherKey="CargaHoraria,Nome", IsForeignKey=true)]
		public ControleHorario ControleHorario
		{
			get
			{
				return this._ControleHorario.Entity;
			}
			set
			{
				ControleHorario previousValue = this._ControleHorario.Entity;
				if (((previousValue != value) 
							|| (this._ControleHorario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ControleHorario.Entity = null;
						previousValue.Funcionario.Remove(this);
					}
					this._ControleHorario.Entity = value;
					if ((value != null))
					{
						value.Funcionario.Add(this);
						this._CargaHoraria = value.CargaHoraria;
						this._Nome = value.Nome;
					}
					else
					{
						this._CargaHoraria = default(string);
						this._Nome = default(string);
					}
					this.SendPropertyChanged("ControleHorario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_CargaHoraria")]
	public partial class Carga_Horaria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_CargaHoraria;
		
		private string _CargaHoraria;
		
		private EntitySet<Funcionario> _Funcionario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_CargaHorariaChanging(int value);
    partial void OnID_CargaHorariaChanged();
    partial void OnCargaHorariaChanging(string value);
    partial void OnCargaHorariaChanged();
    #endregion
		
		public Carga_Horaria()
		{
			this._Funcionario = new EntitySet<Funcionario>(new Action<Funcionario>(this.attach_Funcionario), new Action<Funcionario>(this.detach_Funcionario));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CargaHoraria", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_CargaHoraria
		{
			get
			{
				return this._ID_CargaHoraria;
			}
			set
			{
				if ((this._ID_CargaHoraria != value))
				{
					this.OnID_CargaHorariaChanging(value);
					this.SendPropertyChanging();
					this._ID_CargaHoraria = value;
					this.SendPropertyChanged("ID_CargaHoraria");
					this.OnID_CargaHorariaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CargaHoraria", DbType="NVarChar(50)")]
		public string CargaHoraria
		{
			get
			{
				return this._CargaHoraria;
			}
			set
			{
				if ((this._CargaHoraria != value))
				{
					this.OnCargaHorariaChanging(value);
					this.SendPropertyChanging();
					this._CargaHoraria = value;
					this.SendPropertyChanged("CargaHoraria");
					this.OnCargaHorariaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Carga_Horaria_Funcionario", Storage="_Funcionario", ThisKey="CargaHoraria", OtherKey="CargaHoraria")]
		public EntitySet<Funcionario> Funcionario
		{
			get
			{
				return this._Funcionario;
			}
			set
			{
				this._Funcionario.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Funcionario(Funcionario entity)
		{
			this.SendPropertyChanging();
			entity.Carga_Horaria = this;
		}
		
		private void detach_Funcionario(Funcionario entity)
		{
			this.SendPropertyChanging();
			entity.Carga_Horaria = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_ControleHorario")]
	public partial class ControleHorario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_ControleHorario;
		
		private string _Mês;
		
		private System.Nullable<System.DateTime> _Data;
		
		private System.Nullable<System.TimeSpan> _Entrada;
		
		private System.Nullable<System.TimeSpan> _Intervalo;
		
		private System.Nullable<System.TimeSpan> _Retorno;
		
		private System.Nullable<System.TimeSpan> _Saida;
		
		private string _Nome;
		
		private string _CargaHoraria;
		
		private EntitySet<Funcionario> _Funcionario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_ControleHorarioChanging(int value);
    partial void OnID_ControleHorarioChanged();
    partial void OnMêsChanging(string value);
    partial void OnMêsChanged();
    partial void OnDataChanging(System.Nullable<System.DateTime> value);
    partial void OnDataChanged();
    partial void OnEntradaChanging(System.Nullable<System.TimeSpan> value);
    partial void OnEntradaChanged();
    partial void OnIntervaloChanging(System.Nullable<System.TimeSpan> value);
    partial void OnIntervaloChanged();
    partial void OnRetornoChanging(System.Nullable<System.TimeSpan> value);
    partial void OnRetornoChanged();
    partial void OnSaidaChanging(System.Nullable<System.TimeSpan> value);
    partial void OnSaidaChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnCargaHorariaChanging(string value);
    partial void OnCargaHorariaChanged();
    #endregion
		
		public ControleHorario()
		{
			this._Funcionario = new EntitySet<Funcionario>(new Action<Funcionario>(this.attach_Funcionario), new Action<Funcionario>(this.detach_Funcionario));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ControleHorario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_ControleHorario
		{
			get
			{
				return this._ID_ControleHorario;
			}
			set
			{
				if ((this._ID_ControleHorario != value))
				{
					this.OnID_ControleHorarioChanging(value);
					this.SendPropertyChanging();
					this._ID_ControleHorario = value;
					this.SendPropertyChanged("ID_ControleHorario");
					this.OnID_ControleHorarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mês", DbType="NChar(10)")]
		public string Mês
		{
			get
			{
				return this._Mês;
			}
			set
			{
				if ((this._Mês != value))
				{
					this.OnMêsChanging(value);
					this.SendPropertyChanging();
					this._Mês = value;
					this.SendPropertyChanged("Mês");
					this.OnMêsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data", DbType="Date")]
		public System.Nullable<System.DateTime> Data
		{
			get
			{
				return this._Data;
			}
			set
			{
				if ((this._Data != value))
				{
					this.OnDataChanging(value);
					this.SendPropertyChanging();
					this._Data = value;
					this.SendPropertyChanged("Data");
					this.OnDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Entrada", DbType="Time")]
		public System.Nullable<System.TimeSpan> Entrada
		{
			get
			{
				return this._Entrada;
			}
			set
			{
				if ((this._Entrada != value))
				{
					this.OnEntradaChanging(value);
					this.SendPropertyChanging();
					this._Entrada = value;
					this.SendPropertyChanged("Entrada");
					this.OnEntradaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Intervalo", DbType="Time")]
		public System.Nullable<System.TimeSpan> Intervalo
		{
			get
			{
				return this._Intervalo;
			}
			set
			{
				if ((this._Intervalo != value))
				{
					this.OnIntervaloChanging(value);
					this.SendPropertyChanging();
					this._Intervalo = value;
					this.SendPropertyChanged("Intervalo");
					this.OnIntervaloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Retorno", DbType="Time")]
		public System.Nullable<System.TimeSpan> Retorno
		{
			get
			{
				return this._Retorno;
			}
			set
			{
				if ((this._Retorno != value))
				{
					this.OnRetornoChanging(value);
					this.SendPropertyChanging();
					this._Retorno = value;
					this.SendPropertyChanged("Retorno");
					this.OnRetornoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Saida", DbType="Time")]
		public System.Nullable<System.TimeSpan> Saida
		{
			get
			{
				return this._Saida;
			}
			set
			{
				if ((this._Saida != value))
				{
					this.OnSaidaChanging(value);
					this.SendPropertyChanging();
					this._Saida = value;
					this.SendPropertyChanged("Saida");
					this.OnSaidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="NVarChar(50)")]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CargaHoraria", DbType="NVarChar(50)")]
		public string CargaHoraria
		{
			get
			{
				return this._CargaHoraria;
			}
			set
			{
				if ((this._CargaHoraria != value))
				{
					this.OnCargaHorariaChanging(value);
					this.SendPropertyChanging();
					this._CargaHoraria = value;
					this.SendPropertyChanged("CargaHoraria");
					this.OnCargaHorariaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ControleHorario_Funcionario", Storage="_Funcionario", ThisKey="CargaHoraria,Nome", OtherKey="CargaHoraria,Nome")]
		public EntitySet<Funcionario> Funcionario
		{
			get
			{
				return this._Funcionario;
			}
			set
			{
				this._Funcionario.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Funcionario(Funcionario entity)
		{
			this.SendPropertyChanging();
			entity.ControleHorario = this;
		}
		
		private void detach_Funcionario(Funcionario entity)
		{
			this.SendPropertyChanging();
			entity.ControleHorario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_usuario")]
	public partial class tb_usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _usuario;
		
		private string _senha;
		
		private int _id_usuario;
		
		private string _Acesso;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnusuarioChanging(string value);
    partial void OnusuarioChanged();
    partial void OnsenhaChanging(string value);
    partial void OnsenhaChanged();
    partial void Onid_usuarioChanging(int value);
    partial void Onid_usuarioChanged();
    partial void OnAcessoChanging(string value);
    partial void OnAcessoChanged();
    #endregion
		
		public tb_usuario()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario", DbType="VarChar(50)")]
		public string usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				if ((this._usuario != value))
				{
					this.OnusuarioChanging(value);
					this.SendPropertyChanging();
					this._usuario = value;
					this.SendPropertyChanged("usuario");
					this.OnusuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_senha", DbType="VarChar(50)")]
		public string senha
		{
			get
			{
				return this._senha;
			}
			set
			{
				if ((this._senha != value))
				{
					this.OnsenhaChanging(value);
					this.SendPropertyChanging();
					this._senha = value;
					this.SendPropertyChanged("senha");
					this.OnsenhaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_usuario", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_usuario
		{
			get
			{
				return this._id_usuario;
			}
			set
			{
				if ((this._id_usuario != value))
				{
					this.Onid_usuarioChanging(value);
					this.SendPropertyChanging();
					this._id_usuario = value;
					this.SendPropertyChanged("id_usuario");
					this.Onid_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Acesso", DbType="VarChar(50)")]
		public string Acesso
		{
			get
			{
				return this._Acesso;
			}
			set
			{
				if ((this._Acesso != value))
				{
					this.OnAcessoChanging(value);
					this.SendPropertyChanging();
					this._Acesso = value;
					this.SendPropertyChanged("Acesso");
					this.OnAcessoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
